apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: order-discovery-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-discovery-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: order-sa
    namespace: default
roleRef:
  kind: Role
  name: order-discovery-role
  apiGroup: rbac.authorization.k8s.io